### ISSUE TITLE
Class not recognized

### ISSUE THREAD

**Issue by jvfajardz** [amdecker/obsidian-argdown-plugin#15]
I'm trying to see how to maximize the use of this plug in but I cant seem to figure out how class would work. In below example:

**===
dot:
    graphVizSettings:
        rankdir: LR
        concentrate: true
        ranksep: 0.2
        nodesep: 0.2
===**

Is this because classes is not supported (yet)?

**Comment by amdecker** [comment]
Hi thanks for reaching out! If this is still an issue, can you attach a screenshot of what you see in Obsidian and what you were expecting to see? Did you try properly indenting the configuration?
```
===
dot:
    graphVizSettings:
        rankdir: LR
        concentrate: true
        ranksep: 0.2
        nodesep: 0.2
===
```
